version: "3.5"

services:

  terraform-ansible:
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        - ALPINE_VERSION=${ALPINE_VERSION}
    hostname: webmin-workspace
    environment:
      - TF_VAR_SSH_PUBLIC_KEY=${SSH_PUBLIC_KEY}
      - WEBMIN_ROOT_PASSWORD=${WEBMIN_ROOT_PASSWORD}
    volumes:
      - ./terraform:/terraform
      - ./ansible:/ansible
      - homedir:/root

volumes:
  homedir:
