- name: Añadir el repositorio oficial de Webmin
  shell: |
    curl -o setup-repos.sh https://raw.githubusercontent.com/webmin/webmin/master/setup-repos.sh
    sh setup-repos.sh <<EOF
      y
    EOF
    rm -f setup-repos.sh

- name: Instalar los paquetes necesarios
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - webmin
      - nginx

- name: Copiar el fichero nginx.conf
  ansible.builtin.copy:
    src: /ansible/nginx.conf
    dest: /etc/nginx/sites-enabled/default

- name: Reiniciar nginx
  service:
    name: nginx
    daemon_reload: yes
    state: restarted

- name: Establecer la contrseña del usuario root
  vars:
    user: "root"
    password: "{{ lookup('env', 'WEBMIN_ROOT_PASSWORD') }}"
  ansible.builtin.user:
    name: "{{ user }}"
    state: present
    password: "{{ password | password_hash('sha512') }}"
